name: Quantum Algorithm
on:
  push:
    branches:
      - main

env:
  IBM_TOKEN: ${{ secrets.IBM_TOKEN }}

jobs:
  run-quantum-algorithm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt;
          fi
          wget -qO - --header="X-Papertrail-Token: MVkfhWmx63uxBzZpQ74F" https://papertrailapp.com/destinations/37303101/setup.sh | sudo bash

      - name: Run Shor_algorithm.py
        run: |
          python Shor_algorithm.py 2>&1 | tee /tmp/shor_algorithm_log.txt

      - name: Install Datadog Agent
        run: |
          DD_API_KEY=${{ secrets.DATADOG_API_KEY }}
          DD_SITE="datadoghq.com"
          DD_TAGS="environment:production,service:quantum"
          bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"

      - name: Send Logs to Datadog
        run: |
          echo "Sending Shor's algorithm logs to Datadog..."
          ddtrace -c /etc/datadog-agent/datadog.yaml logs --env=production /tmp/shor_algorithm_log.txt