name: Quantum Algorithm
on:
  push:
    branches:
      - main


env:
  ibm_token: ${{ secerts.IBM_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt;
          fi

      - name: Run main.py
        run: |
          python main.py