name: Quantum Algorithm
on:
  push:
    branches:
      - main

env:
  IBM_TOKEN: ${{ secrets.IBM_TOKEN }}

jobs:
  run-quantum-algorithm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt;
          fi

      - name: Run Shor_algorithm.py
        run: |
          python Shor_algorithm.py

      - name: Install remote_syslog2
        run: |
          wget -O /tmp/remote_syslog2.tar.gz https://github.com/papertrail/remote_syslog2/releases/download/v0.24/remote_syslog_linux_amd64.tar.gz
          tar -xzvf /tmp/remote_syslog2.tar.gz -C /tmp/
          sudo mv /tmp/remote_syslog/remote_syslog /usr/local/bin/

      - name: Send Logs to Papertrail
        run: |
          echo "Sending logs to Papertrail..."
          remote_syslog -p ${{ secrets.PAPERTRAIL_API_KEY }} /var/log/syslog
